/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutBooksImport } from './routes/_layout.books'
import { Route as LayoutDiscoverIndexImport } from './routes/_layout.discover.index'
import { Route as DiscoverRoyalroadChapterSplatImport } from './routes/discover.royalroad.chapter_.$'
import { Route as LayoutDiscoverRoyalroadSplatImport } from './routes/_layout.discover.royalroad.$'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutBooksRoute = LayoutBooksImport.update({
  path: '/books',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDiscoverIndexRoute = LayoutDiscoverIndexImport.update({
  path: '/discover/',
  getParentRoute: () => LayoutRoute,
} as any)

const DiscoverRoyalroadChapterSplatRoute =
  DiscoverRoyalroadChapterSplatImport.update({
    path: '/discover/royalroad/chapter/$',
    getParentRoute: () => rootRoute,
  } as any)

const LayoutDiscoverRoyalroadSplatRoute =
  LayoutDiscoverRoyalroadSplatImport.update({
    path: '/discover/royalroad/$',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/_layout/books': {
      preLoaderRoute: typeof LayoutBooksImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/discover/': {
      preLoaderRoute: typeof LayoutDiscoverIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/discover/royalroad/$': {
      preLoaderRoute: typeof LayoutDiscoverRoyalroadSplatImport
      parentRoute: typeof LayoutImport
    }
    '/discover/royalroad/chapter/$': {
      preLoaderRoute: typeof DiscoverRoyalroadChapterSplatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutBooksRoute,
    LayoutDiscoverIndexRoute,
    LayoutDiscoverRoyalroadSplatRoute,
  ]),
  SettingsRoute,
  DiscoverRoyalroadChapterSplatRoute,
])

/* prettier-ignore-end */
